name: api-stag-workflow
on:
  push:
    branches:
      - master
      - qa1

  workflow_dispatch:

jobs:

  hello:
    if: github.repository == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello hellojob World"
        shell: bash

  
  hello1:
    if: github.repository == 'qa1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello hello1job World"
        shell: bash
