name: api-stag-workflow
on:
  push:
    branches:
      - stagging

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello stagging World"
        shell: bash
