name: api-prod-workflow
on:
  # workflow_dispatch:
  push:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello prod World"
        shell: bash
